### ISSUE TITLE
Sudoku

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/task-mapping#11]
# Instructions
## First pass
- [ ] Choose a task with a blank `phase` column from [tasks](https://docs.google.com/spreadsheets/d/1r6JphHOM8K_dCrdX9ESx_05oYGtPVyVejxKBL1B3VL0/edit#gid=1644218186) and check that it appears to be a valid task entry, e.g. it has a link to a paper and a name etc. Change the `phase` column to `1` in that sheet.
- [ ] Name the issue as the name of the task.
- [ ] Create the issue and assign yourself.
- [ ] Read the linked paper and search through any associated documents or references to find a root source of the task. 
- [ ] Make a new document in the folder [tasks](https://github.com/Watts-Lab/task-mapping/tree/master/tasks) named `{task name}.md` based on the [task-mapping template](https://github.com/Watts-Lab/task-mapping/blob/master/task-representation.md).
- [ ] Save it and add a pull request with the name and message `{task name}`

## Second pass (a different person does this)
- [ ] Add yourself as a secondary assignee to the issue.
- [ ] Read the paper and search through any associated documents or references to find a root source of the task. 
- [ ] Check the PR, making modifications wherever you see necessary to ensure that the task is adequately documented.
- [ ] Check that the template renders correctly by previewing and making any necessary adjustments.
- [ ] When ready, submit a passing review.

## Task mapping (flow in progress contact Mark before starting)
- [ ] First pass assignee: Complete the task mapping survey for this task
- [ ] Second pass assignee: Complete the task mapping survey for this task
- [ ] Reach agreement (check differences, and discuss until both agree on an answer)
- [ ] Merge and close PR.
