### ISSUE TITLE
Recall Associations

### ISSUE THREAD

**Issue by sarikasu** [Watts-Lab/task-mapping#23]
# Summary
> This study was designed to understand collaborative inhibition causes. Researchers compare individual recall (control) to two collaborative group conditions, 
one in which people took turns recalling items together (See Group), the other in which people take turns recalling items but are not aware of the items their partner has recalled (No See Group). Findings show that collaborative inhibition is due to interference caused by the product of recall- sharing answers with each other,
not the process of taking turns without sharing. 

# References
>  Paper Link: https://link.springer.com/article/10.3758/BF03196740
> Papers with Similar Tasks: 
> Productivity Loss In Brainstorming Groups: Toward the Solution of a Riddle
September 1987 Journal of Personality and Social Psychology 53(3):497-509
DOI: 10.1037/0022-3514.53.3.497: https://www.researchgate.net/publication/232602288_Productivity_Loss_In_Brainstorming_Groups_Toward_the_Solution_of_a_Riddle

> Group remembering: does social loafing underlie collaborative inhibition? M S Weldon 1, C Blair, P D Huebsch
PMID: 11185783 DOI: 10.1037//0278-7393.26.6.1568

# Stimuli
> No Visuals Included in paper or appendix but the booklet with words printed in black 20 point font was used 

## Materials for alternative versions of the experiment 
> N/A

# Procedure
## Steps
> Step One: Participants were randomly assigned to one of three conditions with the restriction that there were 20 people in each condition 
        Nominal Condition: participants would work alone to recall words: Tested individually 
        Collaborative Group See Condition: participants worked in pairs and took turns recalling words and were showed the words that 
        each other were recalling. They sat opposite each other at a table
        Collaborative Group No See Condition: participants recalled word lists in pairs, using a turn-taking method however they did not 
        see what word the other recalled
##
> Step Two: Participants are told they will see a list of words that will be tested on later but not told how they will be tested
##
> Step Three: Participants are given a booklet containing a word list, they are told to start on page one and study each word (one word in the middle of each page in 20 point black font). They are not allowed to talk or write anything down during the study period 
##
> Step Four: After the study period, participants completed addition problems for sixty seconds to reduce recency effects
        
## Roles 
> A description of roles if relevant to the task.  
> If relevant, describe how roles are assigned and used in the task. List all roles and list how the experience for each role differs from others.

## Instructions
> NEED TO REACH OUT TO RESEARCHERS 

# Criteria
## Performance calculation
> Performance of each group is determined by the number of words recalled correctly on the recall sheet 

## Incentives
> There were no incentives for the project all participants were volunteers

**Comment by markwhiting** [comment]
I'm adding a few steps for that are in newer versions of the template but not in templates that are already started: 

## Paper mapping
- [ ] First pass assignee: Complete the [claim survey](https://upenn.co1.qualtrics.com/jfe/form/SV_7850rqJDtvCiLHM) for the paper after reading it. 
- [ ] Second pass assignee: Complete the [claim survey](https://upenn.co1.qualtrics.com/jfe/form/SV_7850rqJDtvCiLHM) for the paper after reading it. 

## Task mapping
- [ ] First pass assignee: Complete the [task mapping survey](https://task-robot.glitch.me/survey) entering your GitHub username as the user name, and the task file name as the task name.
- [ ] Second pass assignee: Complete the [task mapping survey](https://task-robot.glitch.me/survey) entering your GitHub username as the user name, and the task file name as the task name.
- [ ] Both assignees: meet to review the [agreement page](https://task-robot.glitch.me/agreement), selecting this task. 
- [ ] Review major disagreements between your responses to check if any are challenging to reconcile. [Schedule a time for both of you to meet with Mark](whiting.me/meet), otherwise, move forward.
- [ ] First pass assignee: In a second browser window start a new [task mapping survey](https://task-robot.glitch.me/survey), this time entering the first then second assignee's GitHub usernames separated by ` | `, e.g., `markwhiting | djwatts`, and the task file name as the task name.
- [ ] Fill in all the agreed responses, and the resolved conflicts.

**Comment by markwhiting** [comment]
Missing instructions.

**Comment by KaranSampath** [comment]
Have we reached out to the researchers for instructions? I can reach out otherwise

**Comment by sarikasu** [comment]
I reached out a few times and didn't get a response, I added in instructions!
