### ISSUE TITLE
Sub-arctic survival

### ISSUE THREAD

**Issue by rafgehrke1** [Watts-Lab/task-mapping#6]
# Instructions
## First pass
- [x] Choose a task with a blank `phase` column from [tasks](https://docs.google.com/spreadsheets/d/1r6JphHOM8K_dCrdX9ESx_05oYGtPVyVejxKBL1B3VL0/edit#gid=1644218186) and check that it appears to be a valid task entry, e.g. it has a link to a paper and a name etc. Change the `phase` column to `1` in that sheet.
- [x] Name the issue as the name of the task.
- [x] Create the issue and assign yourself.
- [x] Read the linked paper and search through any associated documents or references to find a root source of the task. 
- [x] Make a new document in the folder [tasks](https://github.com/Watts-Lab/task-mapping/tree/master/tasks) named `{task name}.md` based on the [task-mapping template](https://github.com/Watts-Lab/task-mapping/blob/master/task-representation.md).
- [x] Save it and add a pull request with the name and message `{task name}`

## Second pass (a different person does this)
- [ ] Add yourself as a secondary assignee to the issue.
- [ ] Read the paper and search through any associated documents or references to find a root source of the task. 
- [ ] Check the PR, making modifications wherever you see necessary to ensure that the task is adequately documented.
- [ ] Check that the template renders correctly by previewing and making any necessary adjustments.
- [ ] When ready, submit a passing review.

## Task mapping (flow in progress contact Mark before starting)
- [ ] First pass assignee: Complete the task mapping survey for this task
- [ ] Second pass assignee: Complete the task mapping survey for this task
- [ ] Reach agreement (check differences, and discuss until both agree on an answer)
- [ ] Merge and close PR.

**Comment by markwhiting** [comment]
I'm adding a few steps for that are in newer versions of the template but not in templates that are already started: 

## Paper mapping
- [ ] First pass assignee: Complete the [claim survey](https://upenn.co1.qualtrics.com/jfe/form/SV_7850rqJDtvCiLHM) for the paper after reading it. 
- [ ] Second pass assignee: Complete the [claim survey](https://upenn.co1.qualtrics.com/jfe/form/SV_7850rqJDtvCiLHM) for the paper after reading it. 

## Task mapping
- [ ] First pass assignee: Complete the [task mapping survey](https://task-robot.glitch.me/survey) entering your GitHub username as the user name, and the task file name as the task name.
- [ ] Second pass assignee: Complete the [task mapping survey](https://task-robot.glitch.me/survey) entering your GitHub username as the user name, and the task file name as the task name.
- [ ] Both assignees: meet to review the [agreement page](https://task-robot.glitch.me/agreement), selecting this task. 
- [ ] Review major disagreements between your responses to check if any are challenging to reconcile. [Schedule a time for both of you to meet with Mark](whiting.me/meet), otherwise, move forward.
- [ ] First pass assignee: In a second browser window start a new [task mapping survey](https://task-robot.glitch.me/survey), this time entering the first then second assignee's GitHub usernames separated by ` | `, e.g., `markwhiting | djwatts`, and the task file name as the task name.
- [ ] Fill in all the agreed responses, and the resolved conflicts.

**Comment by bvikram03** [comment]
What needs to be done on this issue? @katelynbottcher

**Comment by joycewang3** [comment]
> What needs to be done on this issue? @katelynbottcher

Also, the resource paper seems to be not available now. Do you know where we can find it so that we can do the mapping? Thanks!
